In [3]:
import numpy as np

In [ ]:
# 1. Convert List to 1D Array
original_list = [12.23, 13.32, 100, 36.32]
array_1d = np.array(original_list)
print("1. One-dimensional NumPy array:", array_1d)

1. One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [5]:
# 2. Create 3x3 Matrix (2–10)
matrix_3x3 = np.arange(2, 11).reshape(3, 3)
print("\n2. 3x3 matrix:\n", matrix_3x3)


2. 3x3 matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
# 3. Null Vector (10) & Update Sixth Value
null_vector = np.zeros(10)
print("\n3. Null vector:", null_vector)
null_vector[6] = 11
print("Updated vector:", null_vector)


3. Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [8]:

# 4. Array from 12 to 38
array_12_to_38 = np.arange(12, 38)
print("\n4. Array from 12 to 38:", array_12_to_38)



4. Array from 12 to 38: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [9]:

# 5. Convert Array to Float Type
int_array = np.array([1, 2, 3, 4])
float_array = int_array.astype(float)
print("\n5. Array as float type:", float_array)



5. Array as float type: [1. 2. 3. 4.]


In [10]:

# 6. Celsius to Fahrenheit Conversion
celsius = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])
fahrenheit = celsius * 9/5 + 32
print("\n6. Values in Centigrade degrees:", celsius)
print("Values in Fahrenheit degrees:", fahrenheit)



6. Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [11]:

# 7. Append Values to Array
original_array = np.array([10, 20, 30])
appended_array = np.append(original_array, [40, 50, 60, 70, 80, 90])
print("\n7. After appending values:", appended_array)



7. After appending values: [10 20 30 40 50 60 70 80 90]


In [12]:

# 8. Array Statistical Functions
random_array = np.random.rand(10)
mean_val = np.mean(random_array)
median_val = np.median(random_array)
std_dev = np.std(random_array)
print("\n8. Random array:", random_array)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)


8. Random array: [0.13603039 0.20370215 0.89021893 0.01567453 0.52305889 0.08547197
 0.92339763 0.1528542  0.95993963 0.49539715]
Mean: 0.4385745480282298
Median: 0.3495496536121141
Standard Deviation: 0.353989266275197


In [13]:

# 9. Find min and max in 10x10 array
array_10x10 = np.random.rand(10, 10)
min_val = np.min(array_10x10)
max_val = np.max(array_10x10)
print("\n9. 10x10 array min:", min_val)
print("10x10 array max:", max_val)



9. 10x10 array min: 0.01644929705937359
10x10 array max: 0.9818134957142742


In [14]:

# 10. Create a 3x3x3 array with random values
array_3x3x3 = np.random.rand(3, 3, 3)
print("\n10. 3x3x3 array:\n", array_3x3x3)


10. 3x3x3 array:
 [[[0.67969796 0.47886872 0.71447439]
  [0.88542229 0.70349463 0.71215947]
  [0.86384898 0.73239587 0.27166961]]

 [[0.12318988 0.68513991 0.81766445]
  [0.55664123 0.21118956 0.6825363 ]
  [0.61479439 0.22343441 0.15850369]]

 [[0.13288798 0.00538559 0.07096306]
  [0.48277445 0.89295556 0.84945871]
  [0.12998408 0.07674532 0.92326279]]]
